id: P007090
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105795
  title: སྨན་གསོ་འཕྲོད་བསྟེན་སྐོར་གྱི་ཤེས་བྱ།
  author: ''
  volumes:
    9d434b3157074dcc91eb85004de637ed:
      image_group_id: I1PD105797
      title: ''
      volume_number: 1
      total_pages: 142
ebook_metadata:
  title: སྨན་གསོ་འཕྲོད་བསྟེན་སྐོར་གྱི་ཤེས་བྱ།
  author: ''
  sku: P007090
  cover: cover.jpg
  layers:
  - pagination
