id: P007090
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1PD105795
  title: སྨན་གསོ་འཕྲོད་བསྟེན་སྐོར་གྱི་ཤེས་བྱ།
  author: ''
  volumes:
    3d19c7c809194ce5b33c833d812eb868:
      image_group_id: I1PD105797
      title: Volume 1 of sman gso 'phrod bsten skor gyi shes bya
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
