id: I7445AF90
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:27:05+00:00'
last_modified: '2022-06-09T04:46:15.363072+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105795
  title: སྨན་གསོ་འཕྲོད་བསྟེན་སྐོར་གྱི་ཤེས་བྱ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    '7769':
      image_group_id: I1PD105797
      title: Volume 1 of sman gso 'phrod bsten skor gyi shes bya
      total_pages: 142
      order: 1
      base_file: 7769.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
